import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { startServer, credentials } from './helpers.mjs';

const server = await startServer();
let browser;
try {
  browser = await chromium.launch({ ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}), args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1, permissions: ['microphone'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await mkdir('test-results', { recursive: true });
  await page.goto(server.url);
  await page.getByLabel('账号', { exact: true }).fill(credentials.username);
  await page.getByLabel('密码', { exact: true }).fill(credentials.password);
  await page.getByRole('button', { name: '进入我的词库' }).click();
  await expect(page.getByRole('heading', { name: '我的词库。' })).toBeVisible();
  const playbackWords = await page.evaluate(async () => {
    const { saveWord } = await import('/db.js');
    const bytes = new ArrayBuffer(44 + 8000 * 2 * 3);
    const view = new DataView(bytes);
    const text = (offset, value) => [...value].forEach((char, i) => view.setUint8(offset + i, char.charCodeAt(0)));
    text(0, 'RIFF'); view.setUint32(4, bytes.byteLength - 8, true); text(8, 'WAVE'); text(12, 'fmt ');
    view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true);
    view.setUint32(24, 8000, true); view.setUint32(28, 16000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true);
    text(36, 'data'); view.setUint32(40, bytes.byteLength - 44, true);
    const blob = new Blob([bytes], { type: 'audio/wav' });
    return Promise.all(['播放测试甲', '播放测试乙'].map(text => saveWord({ text, note: '', favorite: false }, blob)));
  });
  await page.getByRole('button', { name: '刷新词库' }).click();
  const firstPlay = page.locator(`[data-action="play"][data-id="${playbackWords[0].id}"]`);
  const secondPlay = page.locator(`[data-action="play"][data-id="${playbackWords[1].id}"]`);
  const audioRequests = [];
  let responseMode = 'delay';
  await page.route('**/api/words/*/audio', async route => {
    audioRequests.push(route.request().url());
    const mode = responseMode;
    if (mode === 'fail') { await route.abort(); return; }
    if (mode === 'delay') await new Promise(resolve => setTimeout(resolve, 800));
    await route.continue().catch(() => {});
  });
  await firstPlay.click();
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'loading');
  await expect(firstPlay.locator('.audio-spinner')).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-audio-loading.png', fullPage: true });
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'playing');
  await expect(firstPlay.locator('.audio-bars')).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-audio-playing.png', fullPage: true });
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'idle');
  const loadedRequests = audioRequests.length;
  await firstPlay.click();
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'playing');
  expect(audioRequests.length).toBe(loadedRequests);
  await secondPlay.click();
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'idle');
  await expect(secondPlay).toHaveAttribute('data-audio-state', 'loading');
  await secondPlay.click();
  await expect(secondPlay).toHaveAttribute('data-audio-state', 'idle');
  await page.waitForTimeout(1000);
  await expect(secondPlay).toHaveAttribute('data-audio-state', 'idle');
  responseMode = 'fail';
  await secondPlay.click();
  await expect(page.locator('#toast')).toContainText('播放失败或加载超时');
  await expect(secondPlay).toHaveAttribute('data-audio-state', 'idle');
  responseMode = 'normal';
  await secondPlay.click();
  await expect(secondPlay).toHaveAttribute('data-audio-state', 'playing');
  await secondPlay.click();
  await expect(secondPlay).toHaveAttribute('data-audio-state', 'idle');
  const requestsBeforeUpdate = audioRequests.length;
  await page.evaluate(async id => {
    const { allWords, saveWord } = await import('/db.js');
    const word = (await allWords()).find(word => word.id === id);
    const blob = await (await fetch(`/api/words/${id}/audio`)).blob();
    await saveWord(word, blob);
  }, playbackWords[0].id);
  await page.getByRole('button', { name: '刷新词库' }).click();
  await firstPlay.click();
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'playing');
  expect(audioRequests.length).toBeGreaterThan(requestsBeforeUpdate + 1);
  await page.getByRole('button', { name: '查看或编辑：播放测试甲', exact: true }).click();
  await page.locator('#preview-button').click();
  await expect(page.locator('#preview-button')).toHaveAttribute('data-audio-state', 'playing');
  await page.getByRole('button', { name: '关闭编辑', exact: true }).click();
  await expect(firstPlay).toHaveAttribute('data-audio-state', 'idle');
  await page.unroute('**/api/words/*/audio');
  await page.evaluate(async ids => {
    const { allWords, removeWord } = await import('/db.js');
    for (const word of await allWords()) if (ids.includes(word.id)) await removeWord(word.id, word.version);
  }, playbackWords.map(word => word.id));
  await page.getByRole('button', { name: '刷新词库' }).click();
  await expect(firstPlay).toHaveCount(0);
  const mimeRoundTrip = await page.evaluate(async () => {
    const { saveWord, removeWord } = await import('/db.js');
    const results = [];
    for (const type of ['audio/mp4; codecs="mp4a.40.2"', 'video/mp4; codecs="avc1.42e01e, mp4a.40.2"']) {
      const blob = new Blob(['mime-round-trip'], { type });
      const word = await saveWord({ text: '格式测试', note: '', favorite: false }, blob);
      const response = await fetch(`/api/words/${word.id}/audio`);
      results.push({ status: response.status, data: await response.text() });
      await removeWord(word.id, word.version);
    }
    return results;
  });
  expect(mimeRoundTrip).toEqual([{ status: 200, data: 'mime-round-trip' }, { status: 200, data: 'mime-round-trip' }]);
  await page.screenshot({ path: 'test-results/mobile-empty.png', fullPage: true });
  await page.getByRole('button', { name: '添加字词', exact: true }).click();
  await page.getByLabel('字 / 词').fill('叔叔');
  await page.getByLabel('释义或备注').fill('爸爸的弟弟。先听清楚，再跟着读。');
  await page.getByRole('button', { name: '开始录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('正在录音');
  await page.waitForTimeout(1400);
  await page.getByRole('button', { name: '停止录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('录好了');
  await page.getByRole('button', { name: '试听读音', exact: true }).click();
  await page.getByLabel('收藏这个词').check();
  await page.screenshot({ path: 'test-results/mobile-record.png', fullPage: true });
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.locator('#editor')).not.toBeVisible();
  await expect(page.getByRole('button', { name: '播放：叔叔', exact: true })).toBeVisible();
  const originalAudio = await page.evaluate(async () => {
    const words = await (await fetch('/api/words')).json();
    return Array.from(new Uint8Array(await (await fetch(`/api/words/${words[0].id}/audio`)).arrayBuffer()));
  });
  expect(originalAudio.length).toBeGreaterThan(100);
  await page.getByRole('button', { name: '查看或编辑：叔叔', exact: true }).click();
  await page.getByRole('button', { name: '重新录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('正在录音');
  await page.waitForTimeout(1100);
  await page.getByRole('button', { name: '停止录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('录好了');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: '关闭编辑', exact: true }).click();
  await expect(page.locator('#editor')).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '关闭编辑', exact: true }).click();
  expect(await page.evaluate(async () => {
    const words = await (await fetch('/api/words')).json();
    return Array.from(new Uint8Array(await (await fetch(`/api/words/${words[0].id}/audio`)).arrayBuffer()));
  })).toEqual(originalAudio);
  await page.reload();
  await expect(page.getByRole('button', { name: '播放：叔叔', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '添加字词', exact: true }).click();
  await page.getByLabel('字 / 词').fill('吃饭');
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.getByText('待录音', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '查看或编辑：吃饭', exact: true }).click();
  await page.getByLabel('释义或备注').fill('网络恢复后应能保存');
  await context.setOffline(true);
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.locator('#editor-error')).toContainText('网络连接失败');
  await expect(page.getByLabel('释义或备注')).toHaveValue('网络恢复后应能保存');
  await context.setOffline(false);
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.locator('#editor')).not.toBeVisible();
  await page.getByLabel('搜索字词或备注').fill('网络恢复');
  await expect(page.locator('.word-card')).toHaveCount(1);
  await page.getByLabel('搜索字词或备注').fill('');
  await page.locator('h1').click();
  await page.waitForFunction(() => !document.querySelector('#toast').classList.contains('visible'));
  await page.screenshot({ path: 'test-results/mobile-library.png', fullPage: true });
  for (const width of [320, 375, 390, 430, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  }
  await page.screenshot({ path: 'test-results/desktop-library.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: '温习一下' }).click();
  await expect(page.getByRole('button', { name: '开始复习 · 1 个词' })).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-review-setup.png', fullPage: true });
  await page.getByRole('button', { name: '开始复习 · 1 个词' }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: '答错了' })).toBeDisabled();
  await page.getByRole('button', { name: '听读音，对照一下' }).click();
  await expect(page.getByRole('button', { name: '答错了' })).toBeEnabled();
  await page.screenshot({ path: 'test-results/mobile-review.png', fullPage: true });
  await page.getByRole('button', { name: '答错了' }).click();
  await expect(page.getByRole('heading', { name: '这一轮，完成了。' })).toBeVisible();
  await expect(page.locator('.result-score')).toHaveText('0/ 1 分');
  await page.screenshot({ path: 'test-results/mobile-result.png', fullPage: true });
  await page.getByRole('button', { name: '再练本轮错词' }).click();
  await page.getByRole('button', { name: '听读音，对照一下' }).click();
  await page.getByRole('button', { name: '答对了' }).click();
  await expect(page.getByRole('heading', { name: '这一轮，完成了。' })).toBeVisible();
  await page.getByRole('link', { name: '易错词', exact: true }).click();
  await expect(page.getByText('· 连续答对 1/3')).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-mistakes.png', fullPage: true });
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '标记已掌握' }).click();
  await expect(page.getByRole('heading', { name: '慢慢练，总会记住' })).toBeVisible();
  await page.getByRole('link', { name: '我的词库', exact: true }).click();
  await page.getByRole('button', { name: '查看或编辑：吃饭', exact: true }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '删除词条', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看或编辑：吃饭', exact: true })).toHaveCount(0);
  const secondContext = await browser.newContext();
  const secondPage = await secondContext.newPage();
  await secondPage.goto(server.url);
  await secondPage.getByLabel('账号', { exact: true }).fill(credentials.username);
  await secondPage.getByLabel('密码', { exact: true }).fill(credentials.password);
  await secondPage.getByRole('button', { name: '进入我的词库' }).click();
  await expect(secondPage.getByRole('button', { name: '播放：叔叔', exact: true })).toBeVisible();
  await secondContext.close();
  expect(errors).toEqual([]);
  console.log('浏览器验证通过：录音与试听、持久化、收藏、搜索、断网重试、6 种屏宽、复习计分、易错词和删除。');
} finally { if (browser) await browser.close(); await server.stop(); }
