import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { startServer, credentials } from './helpers.mjs';

const server = await startServer();
let browser;
try {
  browser = await chromium.launch({ ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}), args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1, permissions: ['microphone'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await mkdir('test-results', { recursive: true });
  await page.goto(server.url);
  await page.getByLabel('账号', { exact: true }).fill(credentials.username);
  await page.getByLabel('密码', { exact: true }).fill(credentials.password);
  await page.getByRole('button', { name: '进入我的词库' }).click();
  await expect(page.getByRole('heading', { name: '我的词库。' })).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-empty.png', fullPage: true });
  await page.getByRole('button', { name: '添加字词', exact: true }).click();
  await page.getByLabel('字 / 词').fill('叔叔');
  await page.getByLabel('释义或备注').fill('爸爸的弟弟。先听清楚，再跟着读。');
  await page.getByRole('button', { name: '开始录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('正在录音');
  await page.waitForTimeout(1400);
  await page.getByRole('button', { name: '停止录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('录好了');
  await page.getByRole('button', { name: '试听读音', exact: true }).click();
  await page.getByLabel('收藏这个词').check();
  await page.screenshot({ path: 'test-results/mobile-record.png', fullPage: true });
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.locator('#editor')).not.toBeVisible();
  await expect(page.getByRole('button', { name: '播放：叔叔', exact: true })).toBeVisible();
  const originalAudio = await page.evaluate(async () => {
    const words = await (await fetch('/api/words')).json();
    return Array.from(new Uint8Array(await (await fetch(`/api/words/${words[0].id}/audio`)).arrayBuffer()));
  });
  expect(originalAudio.length).toBeGreaterThan(100);
  await page.getByRole('button', { name: '查看或编辑：叔叔', exact: true }).click();
  await page.getByRole('button', { name: '重新录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('正在录音');
  await page.waitForTimeout(1100);
  await page.getByRole('button', { name: '停止录音', exact: true }).click();
  await expect(page.locator('#record-status')).toContainText('录好了');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: '关闭编辑', exact: true }).click();
  await expect(page.locator('#editor')).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '关闭编辑', exact: true }).click();
  expect(await page.evaluate(async () => {
    const words = await (await fetch('/api/words')).json();
    return Array.from(new Uint8Array(await (await fetch(`/api/words/${words[0].id}/audio`)).arrayBuffer()));
  })).toEqual(originalAudio);
  await page.reload();
  await expect(page.getByRole('button', { name: '播放：叔叔', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '添加字词', exact: true }).click();
  await page.getByLabel('字 / 词').fill('吃饭');
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.getByText('待录音', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '查看或编辑：吃饭', exact: true }).click();
  await page.getByLabel('释义或备注').fill('网络恢复后应能保存');
  await context.setOffline(true);
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.locator('#editor-error')).toContainText('网络连接失败');
  await expect(page.getByLabel('释义或备注')).toHaveValue('网络恢复后应能保存');
  await context.setOffline(false);
  await page.getByRole('button', { name: '保存词条', exact: true }).click();
  await expect(page.locator('#editor')).not.toBeVisible();
  await page.getByLabel('搜索字词或备注').fill('网络恢复');
  await expect(page.locator('.word-card')).toHaveCount(1);
  await page.getByLabel('搜索字词或备注').fill('');
  await page.locator('h1').click();
  await page.waitForFunction(() => !document.querySelector('#toast').classList.contains('visible'));
  await page.screenshot({ path: 'test-results/mobile-library.png', fullPage: true });
  for (const width of [320, 375, 390, 430, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  }
  await page.screenshot({ path: 'test-results/desktop-library.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: '温习一下' }).click();
  await expect(page.getByRole('button', { name: '开始复习 · 1 个词' })).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-review-setup.png', fullPage: true });
  await page.getByRole('button', { name: '开始复习 · 1 个词' }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: '答错了' })).toBeDisabled();
  await page.getByRole('button', { name: '听读音，对照一下' }).click();
  await expect(page.getByRole('button', { name: '答错了' })).toBeEnabled();
  await page.screenshot({ path: 'test-results/mobile-review.png', fullPage: true });
  await page.getByRole('button', { name: '答错了' }).click();
  await expect(page.getByRole('heading', { name: '这一轮，完成了。' })).toBeVisible();
  await expect(page.locator('.result-score')).toHaveText('0/ 1 分');
  await page.screenshot({ path: 'test-results/mobile-result.png', fullPage: true });
  await page.getByRole('button', { name: '再练本轮错词' }).click();
  await page.getByRole('button', { name: '听读音，对照一下' }).click();
  await page.getByRole('button', { name: '答对了' }).click();
  await expect(page.getByRole('heading', { name: '这一轮，完成了。' })).toBeVisible();
  await page.getByRole('link', { name: '易错词', exact: true }).click();
  await expect(page.getByText('· 连续答对 1/3')).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-mistakes.png', fullPage: true });
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '标记已掌握' }).click();
  await expect(page.getByRole('heading', { name: '慢慢练，总会记住' })).toBeVisible();
  await page.getByRole('link', { name: '我的词库', exact: true }).click();
  await page.getByRole('button', { name: '查看或编辑：吃饭', exact: true }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '删除词条', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看或编辑：吃饭', exact: true })).toHaveCount(0);
  const secondContext = await browser.newContext();
  const secondPage = await secondContext.newPage();
  await secondPage.goto(server.url);
  await secondPage.getByLabel('账号', { exact: true }).fill(credentials.username);
  await secondPage.getByLabel('密码', { exact: true }).fill(credentials.password);
  await secondPage.getByRole('button', { name: '进入我的词库' }).click();
  await expect(secondPage.getByRole('button', { name: '播放：叔叔', exact: true })).toBeVisible();
  await secondContext.close();
  expect(errors).toEqual([]);
  console.log('浏览器验证通过：录音与试听、持久化、收藏、搜索、断网重试、6 种屏宽、复习计分、易错词和删除。');
} finally { if (browser) await browser.close(); await server.stop(); }
